services:
  apache:
    container_name: apache
    build: ./docker/apache
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./logs/apache:/var/log/apache2
      - .:/var/www/html
    networks:
      - mathquiz
  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - mathquiz
  mysql:
    container_name: mysql
    image: mysql:8.3.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mathquiz
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8085:80"
    restart: always
    networks:
      - mathquiz
volumes:
  mysql_data:

networks:
  mathquiz:
    driver: bridge
